"""empty message

Revision ID: 9096d4455f29
Revises: 9348d3c4f34b
Create Date: 2018-05-02 16:42:07.754381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9096d4455f29'
down_revision = '9348d3c4f34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'departments', ['password'], unique=True)
    # ### end Alembic commands ###
