"""empty message

Revision ID: 9348d3c4f34b
Revises: a18ba947551f
Create Date: 2018-05-02 16:29:01.994531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9348d3c4f34b'
down_revision = 'a18ba947551f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('password', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'departments', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_column('departments', 'password')
    # ### end Alembic commands ###
